### ISSUE TITLE
Can't control IKEA TRADFRI LED bulb

### ISSUE THREAD

**Issue by Aledan862** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#12]
I successfully paired 6 bulbs. But...
at the broker, I can see only this
topic: `zigbee2mqtt/Ikea1`
payload:
```
 {
  "update_available": false
}
```
![image](https://user-images.githubusercontent.com/40725083/90792830-44677e00-e30b-11ea-8ee1-999e7f34d072.png)
And when I send control message like 
topic: `zigbee2mqtt/Ikea1/set/state`
payload: `ON` (or `OFF`)
Get this error at plugin's log file /plugins/zigbee2mqtt/zigbee2mqtt.log
`error 2020-08-20 17:36:20: Publish 'set' 'state' to 'Ikea1' failed: 'Error: Command 0xec1bbdfffe8c7b61/1 genOnOff.on({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))'
info 2020-08-20 17:36:20: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"zigbee_publish_error","message":"Publish 'set' 'state' to 'Ikea1' failed: 'Error: Command 0xec1bbdfffe8c7b61/1 genOnOff.on({}, {\"timeout\":10000,\"disableResponse\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null}) failed (Data request failed with error: 'No network route' (205))'","meta":{"friendly_name":"Ikea1"}}'`

When I use the same setup with HomeAssistant and Zigbee2Mqtt addon there are no errors when sending the same control message. And on the broker, I see more information at bulb's topic:
![image](https://user-images.githubusercontent.com/40725083/90794461-1e42dd80-e30d-11ea-8809-127a68aad1c2.png)

**Comment by romanlum** [comment]
Can you please check which version of zigbee2mqtt version HomeAssistent is using?
