### ISSUE TITLE
Updating zigbee2mqtt version in zigbee2mqtt 0.4.0 plugin ??

### ISSUE THREAD

**Issue by Valliess** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#14]
Hi, 

@romanlum I was wondering how to update from zigbee2mqtt version 1.14.2 in the 0.4.0 plugin to Z2M 1.15.0?
Is this possible? It doesn't seem to work with "npm i zigbee2mqtt" command and standard loxberry user.

Any hints ? I need the newest devices list from version 1.15.0 to be able to join a security keypad.

Many Thanks

**Comment by romanlum** [comment]
i am currently preparing a new version of zigbee2mqtt with 1.15 inside

**Comment by Valliess** [comment]
but, for us users when really needed, we can't update the z2m version manually ?, is there an easy way to make it possible to auto-update the Z2M version, without to be attached to the plugin version ?

**Comment by Valliess** [comment]
BtW I forgot to mention that this is great work !!
Actually I'm using it but want to expand with a keypad.
Stable, fast and easy...
Thanks !

**Comment by romanlum** [comment]
thanks.

currently not, but i will try to integrate an update feature for z2m in a future release

**Comment by romanlum** [comment]
you can use the dev version if you like:
https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/archive/feature/zigbee2mqtt-upgrade.zip

**Comment by Valliess** [comment]
Hi @romanlum , so far so good. 
I'm working with koenkk to integrate the iris v3 keypad to the zigbee2mqtt devices list. 
To do so, I need to enable the herdsman debug. Koenkk gave me some methods to do this (look into this link: https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging) but to do so in the plugin that you provide, could you give a hint to progress and put the herdsman into debug please?
I'm just looking for the right syntax. 

Thanks for helping a noob.

Valentijn

**Comment by romanlum** [comment]
You can directly edit the configuration file by connecting via ssh to the loxberry.
The configuration is stored in /opt/zigbee2mqtt/data/configuration.yml

After editing the config you can open the webui and click save to restart the service

**Comment by romanlum** [comment]
Current version uses zigbee2mqtt 1.17.1
