### ISSUE TITLE
Cant pair SNZB-03

### ISSUE THREAD

**Issue by rsi-soft** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#18]
Hi,
I have a problem with pairing the device Sonoff ZigBee PIR - SNZB-03. This is on the list of supported devices (https://www.zigbee2mqtt.io/devices/SNZB-03.html). Do you have any idea how to pair this device?
There is log:
info 2020-11-24 19:36:13: Device '0x00124b002247e45c' joined
info 2020-11-24 19:36:13: Starting interview of '0x00124b002247e45c'
info 2020-11-24 19:36:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":{"friendly_name":"0x00124b002247e45c"},"type":"device_connected"}'
info 2020-11-24 19:36:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_started","meta":{"friendly_name":"0x00124b002247e45c"},"type":"pairing"}'
info 2020-11-24 19:36:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x00124b002247e45c"},"type":"device_announced"}'
info 2020-11-24 19:36:24: Successfully interviewed '0x00124b002247e45c', device has successfully been paired
warn 2020-11-24 19:36:24: Device '0x00124b002247e45c' with Zigbee model '66666' is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
info 2020-11-24 19:36:24: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"interview_successful","meta":{"friendly_name":"0x00124b002247e45c","supported":false},"type":"pairing"}'
warn 2020-11-24 19:37:24: Received message from unsupported device with Zigbee model '66666'
warn 2020-11-24 19:37:24: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.

**Comment by romanlum** [comment]
The log states that this device is not supported.
Maybe you should try the new version of the plugin because it uses a newer zigbee2mqtt version

**Comment by romanlum** [comment]
closed because of no further comment
