### ISSUE TITLE
Last Seen Value too large

### ISSUE THREAD

**Issue by JackAAnders** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#22]
Hi Roman,
the last##_seen value provide by zigbee2MQTT is to large to get analyzed by Loxone. Milliseconds since 1971 are quite a lot.
In case of a sensor, I guess it would be sufficient to check that a zigbee device was providing values at a larger timescale. One second is probably far more than enough.
The Velux2MQTT service is handling it the same way.

Is there a possibility to scale this by 1\1000 maybe. Otherwise, Loxone will complain that the value is out of range (-2147483647 .. 2147483647) and this value is not usable.

Reason why I asking for this, the battery status is somewhat not reliable. It could quickly happen that you have a sufficient battery level, but it quickly dies due to low temperature. In this case you are not getting a battery empty warning from the sensor.

regards,
Jack

**Comment by romanlum** [comment]
sorry but it is not possible in the plugin

maybe you can use mqtt transformer for this
see https://loxwiki.atlassian.net/wiki/spaces/LOXBERRY/pages/1268482191/MQTT+Gateway+-+UDP+Transformers
