### ISSUE TITLE
Please fix Zigbee2Mqtt UI deactivation

### ISSUE THREAD

**Issue by lgrawet** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#26]
Hi,

There is a problem with frontend (UI) deactivation. The current way by setting an empty port is unsupported and lead to an error.
The correct way to do it is by setting `frontend: false`, see [official documentation here](https://www.zigbee2mqtt.io/guide/configuration/frontend.html).

Also see my commit [be52aa012f15ff8877d90a4946993dfbc166a16f](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/pull/25/commits/be52aa012f15ff8877d90a4946993dfbc166a16f) part of PR #25 submitted June 30.

Many thanks,

Laurent

**Comment by romanlum** [comment]
thanks for your help

fixed in 1.7
