### ISSUE TITLE
Please Z2mqtt upgrade to 1.28.2

### ISSUE THREAD

**Issue by Kuliss9** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#27]
With the new Loxone Config 13.1. and it's energy monitor I would like to use Silvercrest Smart Plug HG08673. This smart plug is not suported in the last version of this loxberry plugin. Would you be so kind and upgrade Zigbee2Mqtt plugin for Loxberry?

**Comment by romanlum** [comment]
Did you use the current prerelease that uses 1.28.0?

**Comment by romanlum** [comment]
version 1.7 includes 1.28.4
