### ISSUE TITLE
Support for Loxberry ver 3.x.x

### ISSUE THREAD

**Issue by kamil-j** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#28]
Could you please add support for loxberry 3.0.0 and higher? Currently the highest supported version is 2.99 and plugin cannot be installed.

**Comment by madito** [comment]
I have created a pull request for compatibility with LoxBerry 3.0:

https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/pull/30

**Comment by romanlum** [comment]
support added in 1.7-prerelase
