### ISSUE TITLE
Zigbee2MQTT switch to dev branch

### ISSUE THREAD

**Issue by nolsnols** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#31]
Hey, I use the zigbee2mqtt Loxberry plugin and it works like a charm.
I have Avatto TRV  (https://www.zigbee2mqtt.io/devices/TS0601_thermostat_3.html)and they are not supported in the included zigbee2mqtt version.
I find the device in the converters: https://github.com/Koenkk/zigbee-herdsman-converters
device: TS0601 manufactur: _TZE200_bvu2wnxz

Is it possible to switch to the dev branch to have the latest devices supported?

[***](https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by romanlum** [comment]
Thanks for your issue.
No i will not switch to the dev branch because it is maybe not stable.
