### ISSUE TITLE
Zigbee2mqtt do not start with Zigate dongle

### ISSUE THREAD

**Issue by Luckyman40** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#32]
Hello,
I have an issue on a fresh install of loxberry v3.0.0 and your plugin Zigbee2Mqtt v1.7.0 (but same issue with older version of the plugin)
the service do not want to launch and the error is: "Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"
I know this is an known issue but on loxberry i don't know how to solve it .... 
i have tested my dongle on raspbian, i've just specified in the conf file adapter: zigate and it works like a charm but i can not do this on loxberry .... 
i hope you will understand what i mean :) 
thank you for your help !

**Comment by heubi76** [comment]
Same Problem for me. Tried with new install on a RPI4 - 3.0.0.1 / 1.7.0. Install protocol of zigbee run without faults. Cannot start service, starts and stops. Even the log site is not accessible to get any idea of the problem. Any clue?
Regards Heubi

**Comment by romanlum** [comment]
Closed due to inactivity
