### ISSUE TITLE
Zigbee2mqtt not working due to missing php include path

### ISSUE THREAD

**Issue by christophmoar** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#34]
Hi, test setup:
* prerelease version (https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/releases/download/2.0.0/plugin.zip)
* installed on a loxberry 3.0 (qnap virtualization vm, dietpi, loxberry 3.0 installation)

After the installation the admin screen is not capable of reading/writing the configuration.yaml file, thus the server is not starting etc.
Checking apache error log it is due to the include path not being complete and loading of loxberry_system.php fails. The system directory /opt/loxberry/libs/phplib is not included in the php include path

Solution 1:
I added
`include_path = ".:/usr/share/php:/opt/loxberry/libs/phplib"`

In these files:
```
/etc/php/7.4/cli/php.ini
/etc/php/7.4/cgi/php.ini
/etc/php/7.4/apache2/php.ini
```

After this modification installation and configuration will work out.

Other solutions:
You could use loxberrys jsonrpc to get system data;
Or you could use a .htaccess file to setup the php include path;
Or maybe loxberry developers need to be contacted to have /opt/loxberry/libs/phplib included by default - I don't know.

**Comment by romanlum** [comment]
thanks for the bug report i will have a look

**Comment by romanlum** [comment]
@christophmoar i installed loxberry 3.0 on dietpi on a x64 vm and i had no problem with the include path.
which loxberry version did you have? I used the current V3.0.0.3
