### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by juergenarchan** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#46]
Hello, until when will there be a new release (or PreRelease) with version 1.33.0 of zigbee2mqtt? With the current version 1.31.2 I have the problem that the Paulmann controller is not supported. This problem has been resolved in the current PreRelease version 1.32.2. Thank you

**Comment by romanlum** [comment]
If there are no problems with the current prerelease i will release the version about next week.
Then another pre-release with 1.33.0 will  be created

**Comment by juergenarchan** [comment]
Great! Thank you very much

**Comment by romanlum** [comment]
PreRelease 2.4.0 wurde erstellt.
Diese enthält jetzt zigbee2mqtt 1.33.1
