### ISSUE TITLE
Loxberry Plugin Version Placeholder not working

### ISSUE THREAD

**Issue by 3limin4tor** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#53]
![image](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/assets/5002404/e81a0f56-4533-4eab-abc9-84b71e60ebd8)

Pic should say everything, would be nice if you can fix it with the next release, as this is maybe just a very small issue. 

EDIT: Forgot to mention that i‘m using LB 3.0.0.6
Thanks

**Comment by romanlum** [comment]
Should be fixed
