### ISSUE TITLE
IKEA Vallhorn . Motion Sensor - not supported?

### ISSUE THREAD

**Issue by lmuser22** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#54]
On my Loxberry Version 3.0.0.6 with Zigbee2MQTT Version 2.4.0 i cant get my new IKEA Vallhorn Motion Sensor running.
On Home Assistant its running.

![image](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/assets/36540223/3adda1ab-2231-486a-9792-b1aab0c016f5)

**Comment by romanlum** [comment]
Please try with new prerelease 2.6.0
It uses zigbee2mqtt 1.35.3
