### ISSUE TITLE
Innr SP 240 not supportet

### ISSUE THREAD

**Issue by Ch0112** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#55]
Hello everyone,

The smart socket was added to Homeassistant a few weeks ago and is now working. 
But it is not yet running on the Loxberry? Are different people working on the different systems? 
Or has it been forgotten here?
Can it also be activated here or is something else required?

**Comment by matlab22** [comment]
you will need to have the zigbee2mqtt version updated to the version, where your smart socket is supported. This plugin is always behind with updates.
Release 2.4 is on zigbee2mqtt 1.33.1
Prerelease 2.5 is on zigbee2mqtt [1.35.0](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/releases/download/2.5.0/plugin.zip)

while the original master already is on [1.35.3](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.35.3)

**Comment by romanlum** [comment]
created a new prerelease 2.6.0 with zigbee2mqtt 1.35.3
