### ISSUE TITLE
Error installing  php7.4-yaml php7.4-twig g++ - Error 100

### ISSUE THREAD

**Issue by Laserlap** [romanlum/LoxBerry-Plugin-Zigbee2Mqtt#61]
Hello, 

I installed Loxberry (newest version) and tried to install Zigbee2MQTT Plugin afterwards. (3 times)

During the plugin installation I get everytime the following error:
"CRITICAL: Error installing  php7.4-yaml php7.4-twig g++ - Error 100"

Do you have any ideas how to fix?

Hardware Raspberry 4. Raspberry 3b same issue. Installation on another Raspberry 3b in February have been worked fine.

Kind regards
Erik

Log:
```
22:52:23.159 OK: Apt database updated successfully.
22:52:23.267 OK: Apt cache cleaned successfully.
22:52:23.268 INFO: Installing additional software packages.
22:52:23.839 INFO: No process is locking apt or dpkg. Fine.
22:52:23.840 INFO: Installing apt packages  php7.4-yaml php7.4-twig g++...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package php7.4-twig
E: Couldn't find any package by glob 'php7.4-twig'
E: Couldn't find any package by regex 'php7.4-twig'
22:52:41.071 CRITICAL: Error installing  php7.4-yaml php7.4-twig g++ - Error 100
22:52:41.072 WARNING: (Some) Packages could not be installed.
22:52:41.092 INFO: Updating skels for Logfiles in tmpfs.
22:53:05.591 OK: Good bye. Enjoy your new plugin!

```

**Comment by romanlum** [comment]
There is a new prerelease 2.8.0 that should fix the installation issues

**Comment by romanlum** [comment]
Can you please try it out and give me feedback if it works for you?

**Comment by Laserlap** [comment]
installation works for both raspberrys

currently I get "Service stopped (Please check settings and device configuration)" for one these but I will check it later

thank you for the fix

**Comment by Laserlap** [comment]
Service will not start. Still message: "Service stopped (Please check settings and device configuration)"

Raspberry 4 (does not work, new raspberry installation + same issue with a new SD card):
LoxBerry Version 3.0.1.1 ( is_arch_aarch64.cfg is_hwmodel_raspberry_pi_4_400.cfg is_raspberry.cfg )
Zigbee2Mqtt: Version 2.8.1

Raspberry 3b (does not work, new raspberry installation)
INFO: LoxBerry Version 3.0.1.1 ( is_arch_aarch64.cfg is_hwmodel_raspberry_pi_3_3+_zero_2.cfg is_raspberry.cfg )
Zigbee2Mqtt: Version 2.8.1

Raspberry 4 (works, installed in Febrary und Loxberry updated to 3.0.1.1)
LoxBerry Version 3.0.1.1 ( is_arch_aarch64.cfg is_hwmodel_raspberry_pi_4_400.cfg is_raspberry.cfg )
Zigbee2Mqtt: Version 2.8.1

**Comment by romanlum** [comment]
thanks for your feedback.
Can you check/add the zigbee2mqtt logs ?
`/opt/zigbee2mqtt/log/*`

**Comment by Laserlap** [comment]
[20240404_204513_914_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14880797/20240404_204513_914_Service.log)
[20240404_204513_999_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14880798/20240404_204513_999_Service.log)
[20240404_204522_856_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14880799/20240404_204522_856_Service.log)
[20240404_204522_924_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14880800/20240404_204522_924_Service.log)

**Comment by Laserlap** [comment]
I copied the /opt/zigbee2mqtt/folder and I also executed your provided comands (see copied log ssh)


[20240404_204513_914_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14881204/20240404_204513_914_Service.log)
[20240404_204513_999_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14881205/20240404_204513_999_Service.log)
[20240404_204522_856_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14881206/20240404_204522_856_Service.log)
[20240404_204522_924_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14881207/20240404_204522_924_Service.log)
[20240405_085229_211_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14881209/20240405_085229_211_Service.log)
[20240405_085229_285_Service.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14881210/20240405_085229_285_Service.log)
[zigbee2mqtt.log](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14881211/zigbee2mqtt.log)
[copied log ssh.txt](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14881239/copied.log.ssh.txt)

**Comment by romanlum** [comment]
Thanks, but the log `copied-log-ssh.txt`  is empty

**Comment by Laserlap** [comment]
I restarted the raspberry and reconnected the conbee2 and executed your comand

The UI shows still "Service stopped" but the plugin works (I connected a new device)

[new try to start the service.txt](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14881480/new.try.to.start.the.service.txt)

**Comment by romanlum** [comment]
In the first try there was a problem with the conbee2 stick not recognized...

the new try seems to be ok.
Can you check the configuration if the interface is enabled?

**Comment by Laserlap** [comment]
Where can ic find the configuration?
[zigbee2mgtt UI Configuration.docx](https://github.com/romanlum/LoxBerry-Plugin-Zigbee2Mqtt/files/14885035/zigbee2mgtt.UI.Configuration.docx)

PS: 
after restart I have to enter your commands again:
cd /opt/zigbee2mqtt
npm start

**Comment by thing4711** [comment]
I had a very similar issue, probably with the similar cause also.

I just installed newest LoxBerry 3.0.1.1 on a Raspberry Pi 4 Model B Rev 1.5 and did all basic configuration steps.
I then installed as the first addon this Zigbee2Mqtt plugin in version 2.8.1.
Despite correct configuration, and no errors during install, it shows "Service stopped (Please check settings and device configuration)" in LoxBerry GUI.
systemctl status zigbee2mqtt.service confirms this:
```
● zigbee2mqtt.service - zigbee2mqtt
     Loaded: loaded (/etc/systemd/system/zigbee2mqtt.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2024-04-07 15:09:36 CEST; 6s ago
    Process: 2530 ExecStart=/usr/bin/npm start (code=exited, status=203/EXEC)
   Main PID: 2530 (code=exited, status=203/EXEC)
        CPU: 3ms
```

I figured out that npm is only available under /usr/local/bin/npm. Hence, I created a symbolic link of npm in /usr/bin and now it seems to start correctly. Zigbee GUI is not available though, but I remember I had this issue in the past and it suddenly worked some time later, so I will probably wait before I complain about this as well ;-).

**Comment by Laserlap** [comment]
Thanks thing4711 and romanlum. Now it works.

I documented the step which I did (Important: Do not use the UI terminal in loxberry!)

cd /opt/zigbee2mqtt/data
editor configuration.yaml
add the following text after the last parameter:
pan_id: GENERATE
ext_pan_id: GENERATE
network_key: GENERATE

Control+X
Y (save)
Enter


su - root
[root Superuser passwort - see creditial export after loxberry installation]
ln -s /usr/local/bin/npm /usr/bin/npm
ln -s /usr/local/bin/npx /usr/bin/npx
ln -s /usr/local/bin/node /usr/bin/node
ln -s /usr/local/bin/corepack /usr/bin/corepack
